name = "PCF-SMP"
author = "Eloir Corona"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "144363e2f784ca50a185041b4f21980e99b7f8e0fb01f0bafc7d93acfee4d554"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.40-beta"

[options]
acceptable-game-versions = ["26.1", "26.1.1", "26.1.2", "26.2"]
