name = "PCF-SMP"
author = "Eloir Corona"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f78e447aab476482ad560a90e9c0d4e0529d196ee5cdbdf1f27d8f1d6226071"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.40-beta"

[options]
acceptable-game-versions = ["26.1", "26.1.1", "26.1.2", "26.2"]
